VSCREENML = "/Users/yusufadeshina/vscreenml"  # EDIT: change this to match your own local /path/to/vscreenml
# BABEL = '/mnt/shared_applications/openbabel/2.4.1'
BABEL = "/Users/yusufadeshina/miniconda2/envs/rdkit_env/bin/obabel"
CHEMAXON = "/Applications/ChemAxon/JChemSuite/"
ROSETTA_DIR = "/Users/yusufadeshina/Rosetta/main/source"
ROSETTA_BUILD = "macosclangrelease"  # EDIT: change this to match your os
MGLTOOLS = "/Users/yusufadeshina/Downloads/mgltools_i86Darwin9_1.5.6"
BINANA = "/Users/yusufadeshina/Downloads/binana_1_2_0"
OMEGA = "/Applications/OMEGA\ 3.1.2.2.app/Contents/MacOS/bin/omega2"
SZYBKI = "/Applications/SZYBKI\ 1.11.0.2.app/Contents/MacOS/bin/szybki"
CXCALC = "/Applications/ChemAxon/JChemSuite/bin/cxcalc"
