VSCREENML = '/fccc/users/karanicolaslab/adeshiy/vscreenml_uploaded_to_cluster' #EDIT: change this to match your own local /path/to/vscreenml 
BABEL = '/mnt/shared_applications/openbabel/2.4.1'
CHEMAXON = '/fccc/users/karanicolaslab/adeshiy/chemaxon'
ROSETTA_DIR = '/mnt/shared_applications/Rosetta_JKlab/Rosetta'
ROSETTA_BUILD = 'linuxgccrelease' # EDIT: change this to match your os
MGLTOOLS='/mnt/shared_applications/mgltools_x86_64Linux2_1.5.6'
BINANA='~/binana_1_2_0'
OMEGA='/mnt/shared_applications/openeye/bin/omega2'
SZYBKI='~/openeye/bin/szybki'
CXCALC='/mnt/shared_applications/marvin/1.5.6/opt/chemaxon/marvinsuite/bin/cxcalc'
